{% set name = "conda-vendor" %}
{% set version = "0.1.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}
source:
  url: https://github.com/MetroStar/conda-vendor/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 1076e3d115d9aabd79865196bcf0d0ef3c9aa215232bf9395e9369ab84e6d212

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  entry_points:
    - conda-vendor = conda_vendor.__main__:cli

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - conda-lock
    - pyyaml
    - requests
    - click

test:
  imports:
    - conda_vendor

about:
  home: https://github.com/MetroStar/conda-vendor
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Conda Vendor is a tool to create local conda channels and manifests for vendored offline deployments

extra:
  recipe-maintainers:
    - tylerpotts
    - ghoersti
